# Generated by Django 4.2.7 on 2023-11-28 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face', models.ImageField(upload_to='images/', verbose_name='Лицевое изображение')),
                ('name', models.CharField(max_length=40)),
                ('description', models.TextField(max_length=500)),
                ('uncompressed_img', models.ImageField(blank=True, upload_to='images/', verbose_name='Оригинальное изображение')),
                ('object3d', models.FileField(upload_to='files/', verbose_name='3D файл')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('avatar', models.ImageField(upload_to='images/')),
                ('tag', models.CharField(max_length=20, unique=True)),
                ('artworks', models.ManyToManyField(blank=True, related_name='Работы', to='base.artwork')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('date', models.DateField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.user')),
            ],
        ),
        migrations.AddField(
            model_name='artwork',
            name='comments',
            field=models.ManyToManyField(blank=True, null=True, to='base.comment'),
        ),
    ]
