# Generated by Django 4.2.7 on 2023-11-28 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_artwork_date_alter_artwork_object3d'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='comments',
            field=models.ManyToManyField(blank=True, to='base.comment'),
        ),
    ]
