# Generated by Django 4.2.7 on 2023-11-28 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_artwork_comments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Account',
        ),
    ]
