# Generated by Django 4.2.7 on 2023-11-29 11:47

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_user_artworks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='object3d',
            field=models.FileField(blank=True, upload_to='files/', validators=[base.models.validate_file_extension], verbose_name='3D файл'),
        ),
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face', models.ImageField(upload_to='images/', verbose_name='Лицевое изображение')),
                ('title', models.CharField(max_length=40)),
                ('description', models.TextField(max_length=500)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('visitors', models.ManyToManyField(blank=True, related_name='exhibitions', to='base.user')),
            ],
        ),
    ]
