# Generated by Django 4.2.7 on 2023-11-29 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_artwork_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='liked',
            field=models.ManyToManyField(blank=True, related_name='followers', to='base.artwork'),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='visitors',
            field=models.ManyToManyField(blank=True, related_name='favorite', to='base.user'),
        ),
    ]
